name: Cypress-Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start application on server
        run: npm run start > app.log 2>&1 &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command-prefix: npx
          wait-on: 'http://localhost:3000'
